services:
    - docker

before_install:
    - openssl aes-256-cbc -K $encrypted_7c2ebed1ebad_key -iv $encrypted_7c2ebed1ebad_iv -in service-accont.json.enc -out service-accont.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud componenets update kubectl
    - gloud auth activate-service-account --key-file service-account.json

    - docker build -t anoopsehdev/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true anoopsehdev/docker-react npm test

# deploy:
